In [87]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [88]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [89]:
import tensorflow as tf

In [90]:
from keras.preprocessing.image import ImageDataGenerator

In [91]:
tf.__version__

'2.7.0'

In [92]:
#pip install zipfile

In [93]:
import zipfile as zf

In [94]:
files =zf.ZipFile("Training-Set-Land.zip",'r')

In [95]:
files.extractall('Training-Set-Land')

In [96]:
files.close()

In [97]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
training_set = train_datagen.flow_from_directory('Training-Set-Land/Training Set - Barren and Crop/',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

Found 310 images belonging to 2 classes.


In [98]:
file = zf.ZipFile("Test-Final.zip",'r')

In [99]:
file.extractall('Test-Final')

In [100]:
file.close()

In [101]:
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('Test-Final/TestFinal',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'binary')

Found 0 images belonging to 0 classes.


In [1]:
cnn=tf.keras.models.Sequential()
cnn.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,activation='relu',input_shape=[64,64,3]))
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Flatten())
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
cnn.fit(x = training_set, validation_data = test_set, epochs = 40)


NameError: name 'tf' is not defined

In [103]:
import numpy as np
from keras.preprocessing import image
s='Test-Final/TestFinal/'
array=[]
for i in range(20):
    s=s+'imagee'+str(i+1)+'.jpg'
    test_image = image.load_img(s, target_size = (64, 64))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = cnn.predict(test_image)
    training_set.class_indices
    if result[0][0] == 1:
      prediction = 'crop'
      array.append(1)
    else:
      prediction = 'barren'
      array.append(0)
    print(prediction)
    s='Test-Final/TestFinal/'
    

barren
barren
barren
barren
barren
barren
barren
crop
crop
crop
crop
barren
crop
crop
crop
crop
crop
barren
crop
crop


In [104]:
array

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1]

In [105]:
import zipfile as zf
file = zf.ZipFile("Training-Set-Water.zip",'r')
file.extractall("Training-Set-Water")
file.close()

In [106]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
training_set = train_datagen.flow_from_directory('Training-Set-Water/Training Set/',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

Found 720 images belonging to 2 classes.


In [107]:
cnn=tf.keras.models.Sequential()
cnn.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,activation='relu',input_shape=[64,64,3]))
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Flatten())
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
cnn.fit(x = training_set, validation_data = test_set, epochs = 40)


Epoch 1/40
23/23 [==============================] - 11s 443ms/step - loss: 0.7212 - accuracy: 0.5361
Epoch 2/40
23/23 [==============================] - 8s 332ms/step - loss: 0.6798 - accuracy: 0.5958
Epoch 3/40
23/23 [==============================] - 8s 325ms/step - loss: 0.6754 - accuracy: 0.5750
Epoch 4/40
23/23 [==============================] - 8s 336ms/step - loss: 0.6494 - accuracy: 0.6292
Epoch 5/40
23/23 [==============================] - 8s 324ms/step - loss: 0.6287 - accuracy: 0.6458
Epoch 6/40
23/23 [==============================] - 8s 332ms/step - loss: 0.6139 - accuracy: 0.6444
Epoch 7/40
23/23 [==============================] - 7s 323ms/step - loss: 0.5980 - accuracy: 0.6472
Epoch 8/40
23/23 [==============================] - 8s 328ms/step - loss: 0.5465 - accuracy: 0.7000
Epoch 9/40
23/23 [==============================] - 8s 327ms/step - loss: 0.5375 - accuracy: 0.6972
Epoch 10/40
23/23 [==============================] - 8s 329ms/step - loss: 0.5239 - accuracy: 0.708

In [108]:
import numpy as np
from keras.preprocessing import image
s='Test-Final/TestFinal/'
array1=[]
for i in range(20):
    s=s+'imagee'+str(i+1)+'.jpg'
    test_image = image.load_img(s, target_size = (64, 64))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = cnn.predict(test_image)
    training_set.class_indices
    if result[0][0] == 1:
      prediction = 'water'
      array1.append(1)
    else:
      prediction = 'dry'
      array1.append(0)
    print(prediction)
    s='Test-Final/TestFinal/'
    

dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry


In [109]:
import pandas as pd
import numpy as np

In [110]:
df=pd.read_csv('Sample2.csv')

In [111]:
lat=df["Latitude"]
lat=np.array(lat)
lat

array([22.71, 22.34, 21.67, 24.55, 23.86, 23.11, 25.59, 25.22, 23.86,
       23.49, 23.11, 22.42, 22.05, 21.67, 24.55, 23.49, 24.15, 23.78,
       23.11, 22.05])

In [112]:
long=df["Longitude"]
long=np.array(long)
long

array([78.55, 80.36, 79.25, 81.48, 80.36, 81.13, 77.67, 79.52, 77.26,
       79.08, 78.04, 76.93, 78.73, 77.7 , 75.29, 75.99, 74.24, 76.06,
       74.95, 75.64])

In [113]:
import folium

In [114]:
mark_map = folium.Map(Location=[22.1,77.1],tiles = 'Stamen Terrain',zoom_start=6)

In [115]:
for i in range(16):
    if array[i]==0 and array1[i]==0:
        folium.Marker([lat[i],long[i]],popup = 'NWB',icon= folium.Icon(color='red')).add_to(mark_map)
    if array[i]==0 and array1[i]==1:
        folium.Marker([lat[i],long[i]],popup = 'WB',icon= folium.Icon(color='blue')).add_to(mark_map)
    if array[i]==1 and array1[i]==0:
        folium.Marker([lat[i],long[i]],popup = 'NWC',icon= folium.Icon(color='green')).add_to(mark_map)
    if array[i]==1 and array1[i]==1:
        folium.Marker([lat[i],long[i]],popup = 'WC',icon= folium.Icon(color='purple')).add_to(mark_map)

In [116]:
mark_map

In [117]:
array

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1]

In [118]:
array1

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [119]:
cloud=df["Clod Coverage"]
c=np.array(cloud)
c

array([-0.01,  0.67, -0.3 , -0.51,  0.31,  0.5 ,  0.09,  0.12, -0.09,
       -0.06, -0.08,  0.13, -0.13,  0.47, -0.03, -0.09,  0.  , -0.51,
       -0.5 , -0.36])

In [120]:
import folium
mark_map1 = folium.Map(Location=[22.1,77.1],tiles = 'Stamen Terrain',zoom_start=6)

In [121]:
for i in range(16):
    if c[i]<0:
        if c[i]<-0.5:
            folium.CircleMarker([lat[i],long[i]],radius = 15,popup = 'SD',color='red').add_to(mark_map1)
        else :
            folium.CircleMarker([lat[i],long[i]],radius = 15,popup = 'D',color='blue').add_to(mark_map1)
    else :
        if c[i]>0.5:
            folium.CircleMarker([lat[i],long[i]],radius = 15,popup = 'SI',color='green').add_to(mark_map1)
        else :
            folium.CircleMarker([lat[i],long[i]],radius = 15,popup = 'I',color='yellow').add_to(mark_map1)

In [72]:
mark_map1